# Generated by Django 4.0.6 on 2022-07-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
